version: '2'

services:
  smart:
    environment:
     - BASE_URL=http://localhost:9000
    ports:
     - "9000:5000"
  app:
    ports:
     - "9001:5000"
  api:
    ports:
     - "9002:8080"
  tests:
    ports:
     - "9003:5000"
