version: '2'

services:
  smart:
    build:
      context: ./docker-builds/reference-smart
      dockerfile: Dockerfile
    image: syncforscience/reference-smart
    environment:
     - API_SERVER=http://api:8080/baseDstu2
    expose: ["5000"]
    networks:
     - internal
  app:
    build:
      context: ./docker-builds/reference-app
      dockerfile: Dockerfile
    image: syncforscience/reference-app
    expose: ["5000"]
    networks:
     - internal
  landing:
    build:
      context: ./docker-builds/landing-page
      dockerfile: Dockerfile
    image: syncforscience/landing-page
    expose: ["80"]
    networks:
     - internal
  api:
    build:
      context: ./docker-builds/reference-api
      dockerfile: Dockerfile
    image: syncforscience/reference-api
    networks:
     - internal
  tests:
    build:
      context: ./docker-builds/reference-tests
      dockerfile: Dockerfile
    image: syncforscience/reference-tests
    expose: ["5000"]
    networks:
      - internal
  research-app-api:
    build:
      context: ./docker-builds/research-app-api
      dockerfile: Dockerfile
    image: syncforscience/research-app-api
    expose: ["5000"]
    networks:
     - internal

  tasks:
    build:
      context: ./docker-builds/reference-tasks
      dockerfile: Dockerfile
    image: syncforscience/reference-tasks
    networks:
     - internal

networks:
  internal:
    driver: bridge
