version: '2'

services:
  smart:
    build:
      context: ./docker-builds/reference-smart
      dockerfile: Dockerfile
    image: syncforscience/reference-smart
    environment:
     - API_SERVER=http://api:8080/baseDstu2
    expose: ["5000"]
    networks:
     - internal
  smart-stu3:
    build:
      context: ./docker-builds/reference-smart
      dockerfile: Dockerfile
    image: syncforscience/reference-smart
    environment:
     - API_SERVER=http://api-stu3:8080/baseDstu3
    expose: ["5000"]
    networks:
     - internal
  app:
    build:
      context: ./docker-builds/reference-app
      dockerfile: Dockerfile
    image: syncforscience/reference-app
    expose: ["5000"]
    networks:
     - internal
  landing:
    build:
      context: ./docker-builds/landing-page
      dockerfile: Dockerfile
    image: syncforscience/landing-page
    expose: ["80"]
    networks:
     - internal
  api:
    build:
      context: ./docker-builds/reference-api
      dockerfile: Dockerfile
    image: syncforscience/reference-api
    networks:
     - internal
  api-stu3:
    build:
      context: ./docker-builds/reference-api-stu3
      dockerfile: Dockerfile
    image: syncforscience/reference-api-stu3
    networks:
     - internal
  tests:
    build:
      context: ./docker-builds/reference-tests
      dockerfile: Dockerfile
    image: syncforscience/reference-tests
    environment:
     - API_SERVER_DSTU2=http://api:8080/baseDstu2
     - API_SERVER_STU3=http://api-stu3:8080/baseDstu3
    expose: ["5000"]
    networks:
      - internal
  research-app-api:
    build:
      context: ./docker-builds/research-app-api
      dockerfile: Dockerfile
    image: syncforscience/research-app-api
    expose: ["5000"]
    networks:
     - internal
    entrypoint: ""
    command: "./runserver.sh"
  token-introspector:
    build:
      context: ./docker-builds/token-introspector
      dockerfile: Dockerfile
    image: syncforscience/token-introspector
    expose: ["5000"]
    environment:
     - API_SERVER=http://smart:5000/api/fhir
    networks:
     - internal
  tasks:
    build:
      context: ./docker-builds/reference-tasks
      dockerfile: Dockerfile
    image: syncforscience/reference-tasks
    networks:
     - internal
  redirector:
    build:
      context: ./docker-builds/redirector
      dockerfile: Dockerfile
    image: syncforscience/redirector
    environment:
     - UWSGI_PORT=9003
    expose: ["9003"]
    networks:
      internal:
        aliases:
         - tests.dev.syncfor.science

networks:
  internal:
    driver: bridge
