version: '2'

services:
  smart:
    build:
      context: ./docker-builds/reference-smart
      dockerfile: Dockerfile
    image: syncforscience/reference-smart
    environment:
     - API_SERVER=http://api:8080/baseDstu2
     - PORT=80
    expose: ["80"]
    networks:
     - internal
  app:
    build:
      context: ./docker-builds/reference-app
      dockerfile: Dockerfile
    image: syncforscience/reference-app
    networks:
     - internal
  api:
    build:
      context: ./docker-builds/reference-api
      dockerfile: Dockerfile
    image: syncforscience/reference-api
    networks:
     - internal
  tasks:
    build:
      context: ./docker-builds/reference-tasks
      dockerfile: Dockerfile
    image: syncforscience/reference-tasks
    networks:
     - internal

networks:
  internal:
    driver: bridge
