version: '2'

services:
  smart:
    volumes:
     - /config/defaults:/smart-stub/defaults/
    networks:
     - proxy-tier
    environment:
     - BASE_URL=https://portal.demo-test.syncfor.science
     - VIRTUAL_HOST=portal.demo-test.syncfor.science
     - VIRTUAL_NETWORK=nginx-proxy
     - VIRTUAL_PORT=80
     - LETSENCRYPT_HOST=portal.demo-test.syncfor.science
     - LETSENCRYPT_EMAIL=letsencrypt@mg.syncfor.science
  app:
    networks:
     - proxy-tier
    environment:
     - VIRTUAL_HOST=app.demo-test.syncfor.science
     - VIRTUAL_NETWORK=nginx-proxy
     - VIRTUAL_PORT=6543
     - LETSENCRYPT_HOST=app.demo-test.syncfor.science
     - LETSENCRYPT_EMAIL=letsencrypt@mg.syncfor.science
  landing:
    networks:
     - proxy-tier
    environment:
     - VIRTUAL_HOST=demo-test.syncfor.science
     - VIRTUAL_NETWORK=nginx-proxy
     - VIRTUAL_PORT=80
     - LETSENCRYPT_HOST=demo-test.syncfor.science
     - LETSENCRYPT_EMAIL=letsencrypt@mg.syncfor.science
  api:
    volumes:
     - derby:/hapi/target
  tests:
    networks:
     - proxy-tier
    environment:
     - VIRTUAL_HOST=tests.demo-test.syncfor.science
     - VIRTUAL_NETWORK=nginx-proxy
     - VIRTUAL_PORT=5000
     - LETSENCRYPT_HOST=tests.demo-test.syncfor.science
     - LETSENCRYPT_EMAIL=letsencrypt@mg.syncfor.science
    volumes:
      - /config/vendors/:/demo-test-suite/config
  crucible:
    networks:
     - proxy-tier
    environment:
     - VIRTUAL_HOST=crucible.demo-test.syncfor.science
     - VIRTUAL_NETWORK=nginx-proxy
     - VIRTUAL_PORT=80
     - LETSENCRYPT_HOST=crucible.demo-test.syncfor.science
     - LETSENCRYPT_EMAIL=letsencrypt@mg.syncfor.science

networks:
  proxy-tier:
    external:
      name: nginx-proxy

volumes:
  derby: {}
