---
class: !!python/name:auth_proxy.models.user.User
args:
  id: 1
  username: daniel-adams
  password: demo-password
  name: Daniel Adams
---
class: !!python/name:auth_proxy.models.user.User
args:
  id: 2
  username: joseph-ross
  password: demo-password
  name: Joseph Ross
---
class: !!python/name:auth_proxy.models.user.Patient
args:
  user_id: 1
  patient_id: smart-1288992
  name: Daniel Adams
  is_user: True
---
class: !!python/name:auth_proxy.models.user.Patient
args:
  user_id: 1
  patient_id: smart-1032702
  name: Amy Shaw
  is_user: False
---
class: !!python/name:auth_proxy.models.user.Patient
args:
  user_id: 2
  patient_id: smart-1081332
  name: Joseph Ross
  is_user: True
---
class: !!python/name:auth_proxy.models.oauth.Client
args:
  client_id: test-suite
  client_secret: demo-secret-s4s
  name: S4S Test Suite
  _redirect_uris: https://tests.demo.syncfor.science/authorized/
  _default_scopes: launch/patient patient/*.read offline_access
  _security_labels: patient medications allergies immunizations problems procedures vital-signs laboratory smoking
---
class: !!python/name:auth_proxy.models.oauth.Client
args:
  client_id: research-app
  client_secret: demo-secret-s4s
  name: All of Us Research Program
  _redirect_uris: https://app.demo.syncfor.science/authorized http://104.196.214.108:5000/authorized
  _default_scopes: launch/patient patient/*.read offline_access
  _security_labels: patient medications allergies immunizations problems procedures vital-signs laboratory smoking
---
class: !!python/name:auth_proxy.models.oauth.Client
args:
  client_id: api-test
  client_secret: api-secret
  name: All of Us Research Program
  _redirect_uris: https://app.demo.syncfor.science/authorized http://s4s.tomwschneider.com/authorized
  _default_scopes: launch/patient patient/*.read offline_access
  _security_labels: patient medications allergies immunizations problems procedures vital-signs laboratory smoking
